Feature/add storage sanity check for relationship change and relationship template
nmshd/bkb-relationships pull request #21
Opened 2023-02-03 10:58 UTC by JLSRKonk

2023-02-03 11:54 UTC, tnotheis requested changes

2023-02-03 11:54 UTC, tnotheis commented on Relationships.Jobs.SanityCheck.RelationshipChange/Infrastructure/Reporter/LogReporter.cs
> +                _logger.LogError("Relationship Change Sanity Check failed. No blob found for relationship change id: {databaseId}", databaseId);
Actually, the sanity check didn't fail. It's job is to find errors, and that's what it did. So I would delete this first sentence.

2023-02-03 11:54 UTC, tnotheis commented on Relationships.Jobs.SanityCheck.RelationshipChange/Infrastructure/Reporter/LogReporter.cs
> +        private readonly List<string> _responseblobids;
Can you please stick to camel casing and just write everything in lowercase?

2023-02-03 11:54 UTC, tnotheis commented on Relationships.Jobs.SanityCheck.RelationshipChange/Infrastructure/Reporter/LogReporter.cs
> +        private readonly List<string> _responseblobids;
Is there a need to divide the ids into to two lists? You can tell from the postfix (_Req/_Res) whether it's a request or response id.

2023-02-03 11:54 UTC, tnotheis commented on Relationships.Jobs.SanityCheck.RelationshipChange/Infrastructure/SanityCheck/SanityCheck.cs
> +                           .Select(u => u.Replace(REQUEST_POSTFIX, String.Empty));
By removing the postfix you don't have the blob id anymore. You should leave the postfix and rather change the code that checks if the database id exists in the blob storage

2023-02-03 11:54 UTC, tnotheis commented on Relationships.Jobs.SanityCheck.RelationshipTemplate/Infrastructure/Reporter/LogReporter.cs
> +                _logger.LogError("Relationship Template Sanity Check failed. No blob found for relationship template id: {databaseId}", databaseId);
Here you should remove the first sentence as well.

2023-02-03 11:54 UTC, tnotheis commented on Relationships.Jobs.SanityCheck.RelationshipChange/Infrastructure/Reporter/IReporter.cs
> +        void ReportOrphanedResponseBlobId(string id);
There should only be one ReportOrphanedBlobId method.

2023-02-06 09:06 UTC, JLSRKonk commented on Relationships.Jobs.SanityCheck.RelationshipChange/Infrastructure/Reporter/LogReporter.cs
> +        private readonly List<string> _responseblobids;
So if I understood correctly, I should use Camel Casing for all names, and write the logs in lower case, right?

2023-02-06 09:07 UTC, JLSRKonk commented on Relationships.Jobs.SanityCheck.RelationshipChange/Infrastructure/Reporter/LogReporter.cs
> +                _logger.LogError("Relationship Change Sanity Check failed. No blob found for relationship change id: {databaseId}", databaseId);
The sanity checks for the other services also need this change, should I create another PR for each of them?

2023-02-06 11:27 UTC, tnotheis commented on Relationships.Jobs.SanityCheck.RelationshipChange/Infrastructure/Reporter/LogReporter.cs
> +        private readonly List<string> _responseblobids;
Oh, there is a "not" missing in my sentence. That doesn't make any sense, of course. 😆 

> and **not** just write everything in lowercase?

2023-02-06 11:29 UTC, tnotheis commented on Relationships.Jobs.SanityCheck.RelationshipChange/Infrastructure/Reporter/LogReporter.cs
> +                _logger.LogError("Relationship Change Sanity Check failed. No blob found for relationship change id: {databaseId}", databaseId);
Not necessary for now. You can take note of that and fix it after I moved the sanity checks to the monolith, so you don't need to create multiple PRs.

2023-02-06 14:54 UTC, tnotheis requested changes

2023-02-06 14:54 UTC, tnotheis commented on Relationships.Jobs.SanityCheck.RelationshipChange/Infrastructure/SanityCheck/SanityCheck.cs
> +                var postfixedDabataseId = databaseId.ToString() + REQUEST_POSTFIX;
Funny typo: "DabataseId" 😆

2023-02-06 14:54 UTC, tnotheis commented on Relationships.Jobs.SanityCheck.RelationshipChange/Infrastructure/SanityCheck/SanityCheck.cs
> +            Func<string, bool> noCorrespondingBlobIdExists = databaseId => _blobIds.All(blobId => blobId != databaseId);
You should combine this predicate and the one in the Where-statement below.

2023-02-06 14:54 UTC, tnotheis commented on Relationships.Jobs.SanityCheck.RelationshipChange/Infrastructure/SanityCheck/SanityCheck.cs
> +                var postfixedDabataseId = databaseId.ToString() + REQUEST_POSTFIX;
You don't check for the response content (`+ RESPONSE_POSTFIX`) at the moment.

2023-02-06 14:54 UTC, tnotheis commented on Relationships.Jobs.SanityCheck.RelationshipChange/Infrastructure/SanityCheck/SanityCheck.cs
> +                var postfixedDabataseId = databaseId.ToString() + REQUEST_POSTFIX;
You should definitely write a test for that case as well

2023-02-06 16:18 UTC, JLSRKonk commented on Relationships.Jobs.SanityCheck.RelationshipChange/Infrastructure/SanityCheck/SanityCheck.cs
> +                var postfixedDabataseId = databaseId.ToString() + REQUEST_POSTFIX;
In the Jira issue, it is stated that we shouldn't check the responses as they are optional and may cause false positives but maybe there should be no problem if we do something like this?

```
private IEnumerable<RelationshipChangeId> GetOrphanedDatabaseIds()
        {
            Func<string, bool> noCorrespondingBlobIdExists = databaseId => _blobIds.All(blobId => blobId != databaseId);

            return _databaseIds.Where(databaseId => noCorrespondingBlobIdExists(databaseId.ToString() + REQUEST_POSTFIX) &&
                                                    noCorrespondingBlobIdExists(databaseId.ToString() + RESPONSE_POSTFIX));
        }
```
Or maybe we can ditch the (`+ SOMETHING_POSTFIX`) and go for a .Contains like in `GetOrphanedBlobIds()`?

2023-02-06 16:36 UTC, tnotheis commented on Relationships.Jobs.SanityCheck.RelationshipChange/Infrastructure/SanityCheck/SanityCheck.cs
> +                var postfixedDabataseId = databaseId.ToString() + REQUEST_POSTFIX;
You're right, I'm stupid. ;-) 
But now that I think about it: you should be able to check that for each BlobId there is a corresponding DatabaseId. Only the other way round can cause problems.

2023-02-06 16:51 UTC, JLSRKonk commented on Relationships.Jobs.SanityCheck.RelationshipChange/Infrastructure/SanityCheck/SanityCheck.cs
> +                var postfixedDabataseId = databaseId.ToString() + REQUEST_POSTFIX;
Makes sense. Do you think I should commit the change above (for every DatabaseId, check if there is at least one response or request blob), or should I just leave it like it was before (for every DatabaseId, check if there is a request blob)?

2023-02-07 06:15 UTC, tnotheis commented on Relationships.Jobs.SanityCheck.RelationshipChange/Infrastructure/SanityCheck/SanityCheck.cs
> +                var postfixedDabataseId = databaseId.ToString() + REQUEST_POSTFIX;
This would result in the same output, wouldn't it? Because the request blob is always required, and the response blob is always optional. So as soon as there is a request blob, the condition would be fulfilled, no matter if there is a response blob or not.

2023-02-07 10:00 UTC, tnotheis requested changes

2023-02-07 10:00 UTC, tnotheis commented on Relationships.Jobs.SanityCheck.RelationshipChange/Infrastructure/SanityCheck/SanityCheck.cs
> +            return _databaseIds.Where(databaseId => noCorrespondingBlobIdExists(databaseId.ToString() + REQUEST_POSTFIX));
```suggestion
            Func<string, bool> noCorrespondingBlobIdExists = databaseId => _blobIds.All(blobId => blobId != databaseId + REQUEST_POSTFIX);

            return _databaseIds.Where(noCorrespondingBlobIdExists(databaseId);
```

2023-02-07 10:00 UTC, tnotheis commented on Relationships.Jobs.SanityCheck.Tests/Tests/SanityCheckTestsRelationshipChange.cs
> +}
Can you add a test that checks that a missing Response content is not reported?

2023-02-07 11:01 UTC, JLSRKonk commented on Relationships.Jobs.SanityCheck.RelationshipChange/Infrastructure/SanityCheck/SanityCheck.cs
> +            return _databaseIds.Where(databaseId => noCorrespondingBlobIdExists(databaseId.ToString() + REQUEST_POSTFIX));
Just to be sure, even though this looks better wouldn't it have an impact on performance? If I'm not mistaken, this would need to generate the `(databaseId + REQUEST_POSTFIX)` string for every blob for each databaseId, no? Or is this a non issue?

2023-02-07 11:10 UTC, tnotheis commented on Relationships.Jobs.SanityCheck.RelationshipChange/Infrastructure/SanityCheck/SanityCheck.cs
> +            return _databaseIds.Where(databaseId => noCorrespondingBlobIdExists(databaseId.ToString() + REQUEST_POSTFIX));
My general rule of thumb is to not care for performance until it's actually a problem. In most cases this is totally sufficient. In this case, let's say that my suggestion would cause a performance drop by about 1 nanosecond per Id. If there are 1 million ids, this would mean that it's 1,000,000 ns in total => <1,000ms => 1s. And since the sanity checks will run in the background at night, this will not harm anybody. That's why I prefer readability of the code in this case.

But I'm glad you asked. 👍

2023-02-07 12:09 UTC, tnotheis submitted a review, later dismissed

2023-02-07 13:25 UTC, tnotheis approved these changes

2023-02-07 13:29 UTC, merged